version: '3.8'

services:
  backend:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: >
        mysql+pymysql://bFtACnJj7Eu9NWP.root:${DB_PASSWORD}
        @gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/${DB_NAME}
        ?ssl_ca=/app/certs/isrgrootx1.pem
        &ssl_verify_cert=true
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "False"
    ports:
      - "8000:8000"
    volumes:
      - ./certs:/app/certs:ro
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
